//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace torque.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("torque.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _14494 {
            get {
                object obj = ResourceManager.GetObject("14494", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2 {
            get {
                object obj = ResourceManager.GetObject("2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _41GBgteobapIljnz18YL67Qhl6w2C3om1_44mMdk273mzogaV4DplvouQpVo5_AIxgU8J0cOM3E3mLZ6_ghgBgCMSCsF2fqYMetaIf5ZBkOKEcDy1d9ZYGuZSaxgPx8WVHZ6ZT3bxx2e {
            get {
                object obj = ResourceManager.GetObject("41GBgteobapIljnz18YL67Qhl6w2C3om1+44mMdk273mzogaV4DplvouQpVo5_AIxgU8J0cOM3E3mLZ6+" +
                        "ghgBgCMSCsF2fqYMetaIf5ZBkOKEcDy1d9ZYGuZSaxgPx8WVHZ6ZT3bxx2e", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AblTX72rjKN4g4_3EF42h5vMXjG_bi5wjj9MxYjw2jgSW7HParttH2yi4_yAEICLPc_SVFkSwSM69l3n3AHECgXg94VJWPwSCiMz3RsontjoSXy7acaiCjzBl6rQwtAwtDqrUBEHzRDS {
            get {
                object obj = ResourceManager.GetObject("AblTX72rjKN4g4+3EF42h5vMXjG_bi5wjj9MxYjw2jgSW7HParttH2yi4_yAEICLPc_SVFkSwSM69l3n3" +
                        "AHECgXg94VJWPwSCiMz3RsontjoSXy7acaiCjzBl6rQwtAwtDqrUBEHzRDS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blackoutline {
            get {
                object obj = ResourceManager.GetObject("blackoutline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lgn {
            get {
                object obj = ResourceManager.GetObject("lgn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lgn1 {
            get {
                object obj = ResourceManager.GetObject("lgn1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lgnhaha {
            get {
                object obj = ResourceManager.GetObject("lgnhaha", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NAF5XCYS {
            get {
                object obj = ResourceManager.GetObject("NAF5XCYS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nmcbtn {
            get {
                object obj = ResourceManager.GetObject("nmcbtn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nmcbtn1 {
            get {
                object obj = ResourceManager.GetObject("nmcbtn1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OyktfnS9qru2Na4PvQdE_mf038dQKe802_JYuufJiYsOIr3rqnGxAmE6QuSRhc8xoTT2kOLHJfZtcca583HRaZyM5iZfxG5SPWzWd6Cm7KDqinLvjUaHpM5e2ckPB8f88csnDPI0uvfq {
            get {
                object obj = ResourceManager.GetObject("OyktfnS9qru2Na4PvQdE_mf038dQKe802+JYuufJiYsOIr3rqnGxAmE6QuSRhc8xoTT2kOLHJfZtcca58" +
                        "3HRaZyM5iZfxG5SPWzWd6Cm7KDqinLvjUaHpM5e2ckPB8f88csnDPI0uvfq", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap P3YG4EQJ {
            get {
                object obj = ResourceManager.GetObject("P3YG4EQJ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap psb {
            get {
                object obj = ResourceManager.GetObject("psb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap qq {
            get {
                object obj = ResourceManager.GetObject("qq", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap qq1 {
            get {
                object obj = ResourceManager.GetObject("qq1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sgn {
            get {
                object obj = ResourceManager.GetObject("sgn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sgnu {
            get {
                object obj = ResourceManager.GetObject("sgnu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tark_shaba {
            get {
                object obj = ResourceManager.GetObject("tark shaba", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TGQA3OQJ {
            get {
                object obj = ResourceManager.GetObject("TGQA3OQJ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tkshaba {
            get {
                object obj = ResourceManager.GetObject("tkshaba", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap torak {
            get {
                object obj = ResourceManager.GetObject("torak", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap torak1 {
            get {
                object obj = ResourceManager.GetObject("torak1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap torqe {
            get {
                object obj = ResourceManager.GetObject("torqe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap us2 {
            get {
                object obj = ResourceManager.GetObject("us2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap white {
            get {
                object obj = ResourceManager.GetObject("white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap whs {
            get {
                object obj = ResourceManager.GetObject("whs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap XSYPZEXP {
            get {
                object obj = ResourceManager.GetObject("XSYPZEXP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap YTQhnGkV9mvG4RO9Y6umiwPdGeaHLWuCaK5HKqjJztJy2yLcblVFZZLD0H1PWUf2tgiiwDnF4Nd2kuDyfVMTgsy_WwUmiLGw_8OWmvkjyfucx_eZtHoJXag4WFwv83COOsvXdFW6AqBe {
            get {
                object obj = ResourceManager.GetObject("YTQhnGkV9mvG4RO9Y6umiwPdGeaHLWuCaK5HKqjJztJy2yLcblVFZZLD0H1PWUf2tgiiwDnF4Nd2kuDyf" +
                        "VMTgsy+WwUmiLGw+8OWmvkjyfucx_eZtHoJXag4WFwv83COOsvXdFW6AqBe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
